kind: Namespace
apiVersion: v1
metadata:
  name: frontend
  labels:
    name: frontend
---
kind: Namespace
apiVersion: v1
metadata:
  name: channel
  labels:
    name: channel
---
kind: Namespace
apiVersion: v1
metadata:
  name: system
  labels:
    name: system